"""hobby column updated

Revision ID: e863b222b3f3
Revises: e1ac03a64ae9
Create Date: 2024-01-05 10:24:51.009935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e863b222b3f3'
down_revision = 'e1ac03a64ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hobby', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('hobby')

    # ### end Alembic commands ###
